//
//  UnisonGameFFI.h
//  UnisoniOS
//
//  C FFI interface to any Rust game built with unison-ios.
//  These functions are generated by the `export_game!` macro
//  and compiled into the game's static library.
//

#ifndef UnisonGameFFI_h
#define UnisonGameFFI_h

#include <stdint.h>

/// Initialize the game engine. Returns an opaque pointer to the game state.
/// @param device  Raw MTLDevice pointer (id<MTLDevice>)
/// @param layer   Raw CAMetalLayer pointer
/// @param width   Initial drawable width in pixels
/// @param height  Initial drawable height in pixels
void* game_init(void* device, void* layer, float width, float height);

/// Run one frame: fixed-timestep physics updates + render.
/// @param state    Pointer returned by game_init
/// @param dt       Time since last frame in seconds
/// @param drawable Raw CAMetalDrawable pointer (id<CAMetalDrawable>) from MTKView.currentDrawable
void game_frame(void* state, float dt, void* drawable);

/// Notify the game of a screen resize.
/// @param state  Pointer returned by game_init
/// @param width  New drawable width in pixels
/// @param height New drawable height in pixels
void game_resize(void* state, float width, float height);

/// Feed a touch-began event.
void game_touch_began(void* state, uint64_t id, float x, float y);

/// Feed a touch-moved event.
void game_touch_moved(void* state, uint64_t id, float x, float y);

/// Feed a touch-ended event.
void game_touch_ended(void* state, uint64_t id);

/// Feed a touch-cancelled event.
void game_touch_cancelled(void* state, uint64_t id);

/// Set the input axis value (e.g., from a virtual joystick).
/// @param x  Horizontal axis, -1.0 (left) to 1.0 (right)
/// @param y  Vertical axis, -1.0 (down) to 1.0 (up)
void game_set_axis(void* state, float x, float y);

/// Destroy the game state and free memory. Do not use the pointer after this call.
void game_destroy(void* state);

/// Return the opaque `Engine` pointer owned by the game state. Used by Swift
/// to call `engine_audio_suspend` / `engine_audio_resume_system` on
/// AVAudioSession interruptions. Returns NULL if `state` is NULL.
void* game_engine_ptr(void* state);

#endif /* UnisonGameFFI_h */
