//! `scripted_game_entry!` macro — the canonical single-call scaffold for a
//! Lua game's `lib.rs`.
//!
//! Replaces the old per-platform boilerplate (web `#[wasm_bindgen(start)]`,
//! iOS `export_game!`, Android `export_game!`, WASM libc init). A game's
//! entire `lib.rs` becomes:
//!
//! ```ignore
//! mod assets { include!(concat!(env!("OUT_DIR"), "/assets.rs")); }
//!
//! unison_scripting::scripted_game_entry!("scripts/main.lua", assets::ASSETS);
//! ```
//!
//! The macro emits per-platform entry points. The game crate is expected to
//! have cargo features `web` / `ios` / `android` that each toggle the
//! matching `unison-scripting` feature (so `wasm-bindgen`, `unison-web`,
//! `unison-ios`, `unison-android`, `jni` etc. are pulled in alongside). Only
//! the enabled platform(s) contribute code; the others compile to nothing.
//!
//! The `#[cfg(feature = "...")]` gates inside the macro expansion are
//! evaluated against the **game crate's** features (not `unison-scripting`'s),
//! because a `macro_rules!` expansion is compiled as if it were written at the
//! call site.

/// Generate all platform entry points for a Lua-scripted game.
///
/// # Arguments
///
/// - `$script_path` — asset path to the main Lua script, e.g. `"scripts/main.lua"`
/// - `$assets_expr` — expression evaluating to `&'static [unison2d::assets::EmbeddedAsset]`
///   (typically the `ASSETS` const generated by `unison_assets::build::embed_assets`)
///
/// # Requirements
///
/// The game crate must declare cargo features `web`, `ios`, and `android`
/// that activate the matching `unison-scripting` features. The `web`
/// feature must also pull in a direct `wasm-bindgen` dep, because the
/// `#[wasm_bindgen(start)]` proc-macro emits absolute `::wasm_bindgen`
/// paths in its expansion. Example:
///
/// ```toml
/// [dependencies]
/// unison-scripting = { version = "…", features = ["simd"] }
/// wasm-bindgen     = { version = "0.2", optional = true }
///
/// [features]
/// default = ["web"]
/// web     = ["unison-scripting/web", "dep:wasm-bindgen"]
/// ios     = ["unison-scripting/ios"]
/// android = ["unison-scripting/android"]
/// ```
///
/// # Example
///
/// ```ignore
/// // project/lib.rs — the entire game scaffold
/// mod assets { include!(concat!(env!("OUT_DIR"), "/assets.rs")); }
///
/// unison_scripting::scripted_game_entry!("scripts/main.lua", assets::ASSETS);
/// ```
#[macro_export]
macro_rules! scripted_game_entry {
    ($script_path:expr, $assets_expr:expr $(,)?) => {
        /// Factory used by every platform entry point below.
        #[allow(dead_code)]
        fn __new_scripted_game() -> $crate::ScriptedGame {
            $crate::ScriptedGame::from_asset($script_path, $assets_expr)
        }

        // ─── Web ──────────────────────────────────────────────────────────
        //
        // Note: `#[wasm_bindgen(start)]` must be reachable by its bare name at
        // the call site, because the proc-macro expansion emits absolute
        // `::wasm_bindgen::...` paths internally. The game crate is therefore
        // expected to have a direct `wasm-bindgen` dep gated on its `web`
        // feature. All other reexports flow through `$crate::reexports`.
        #[cfg(all(feature = "web", target_arch = "wasm32"))]
        #[::wasm_bindgen::prelude::wasm_bindgen(start)]
        pub fn __unison_main() {
            // Route Rust panics to the browser console.
            $crate::reexports::console_error_panic_hook::set_once();
            // Install the JS-side exception bridge used by the patched Lua
            // `luaD_throw` / `luaD_rawrunprotected` on wasm32.
            $crate::wasm_libc::init_lua_error_handler();
            $crate::reexports::unison_web::run(__new_scripted_game());
        }

        // ─── iOS ──────────────────────────────────────────────────────────
        #[cfg(feature = "ios")]
        $crate::reexports::unison_ios::export_game!(
            $crate::ScriptedGame,
            __new_scripted_game()
        );

        // ─── Android ──────────────────────────────────────────────────────
        #[cfg(feature = "android")]
        $crate::reexports::unison_android::export_game!(
            $crate::ScriptedGame,
            __new_scripted_game()
        );
    };
}
