//! Build-time asset embedding.
//!
//! Call [`embed_assets`] from your game's `build.rs` to walk an asset directory,
//! gzip-compress each file, and generate a Rust source file that embeds them
//! via `include_bytes!`.
//!
//! ```ignore
//! // build.rs
//! fn main() {
//!     unison_assets::build::embed_assets("project/assets", "assets.rs");
//! }
//! ```

use flate2::write::GzEncoder;
use flate2::Compression;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

/// Walk `asset_dir` recursively, gzip each file, and write a generated Rust
/// source file to `$OUT_DIR/{output_filename}`.
///
/// The generated file contains:
/// ```ignore
/// pub const ASSETS: &[(&str, &[u8])] = &[
///     ("textures/donut-pink.png", include_bytes!("/abs/path/to/compressed.gz")),
///     // ...
/// ];
/// ```
///
/// # Panics
/// Panics if `asset_dir` doesn't exist or any file can't be read/compressed.
pub fn embed_assets(asset_dir: &str, output_filename: &str) {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set (must be called from build.rs)");
    let out_path = Path::new(&out_dir);

    let asset_root = Path::new(asset_dir)
        .canonicalize()
        .unwrap_or_else(|e| panic!("Asset directory '{}' not found: {}", asset_dir, e));

    // Collect all files recursively
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    walk_dir(&asset_root, &asset_root, &mut entries);
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    // Compress each file and write to OUT_DIR
    let compressed_dir = out_path.join("_assets_compressed");
    fs::create_dir_all(&compressed_dir).expect("Failed to create compressed assets dir");

    let mut generated = String::new();
    generated.push_str("/// Embedded asset table generated by unison-assets build.rs.\n");
    generated.push_str("/// Do not edit — regenerated on every build.\n");
    generated.push_str("pub const ASSETS: &[(&str, &[u8])] = &[\n");

    for (rel_path, abs_path) in &entries {
        let raw = fs::read(abs_path)
            .unwrap_or_else(|e| panic!("Failed to read '{}': {}", abs_path.display(), e));

        // Gzip compress
        let mut encoder = GzEncoder::new(Vec::new(), Compression::best());
        encoder.write_all(&raw)
            .unwrap_or_else(|e| panic!("Failed to compress '{}': {}", rel_path, e));
        let compressed = encoder.finish()
            .unwrap_or_else(|e| panic!("Failed to finish compression for '{}': {}", rel_path, e));

        // Write compressed file to OUT_DIR
        let safe_name = rel_path.replace('/', "__").replace('\\', "__");
        let gz_path = compressed_dir.join(format!("{}.gz", safe_name));
        fs::write(&gz_path, &compressed)
            .unwrap_or_else(|e| panic!("Failed to write compressed '{}': {}", gz_path.display(), e));

        generated.push_str(&format!(
            "    (\"{}\", include_bytes!(\"{}\")),\n",
            rel_path,
            gz_path.display().to_string().replace('\\', "/")
        ));

        // Tell cargo to rerun if this asset changes
        println!("cargo:rerun-if-changed={}", abs_path.display());
    }

    generated.push_str("];\n");

    let output_file = out_path.join(output_filename);
    fs::write(&output_file, &generated)
        .unwrap_or_else(|e| panic!("Failed to write generated file: {}", e));

    // Rerun if the asset directory structure changes
    println!("cargo:rerun-if-changed={}", asset_dir);
}

/// Recursively walk a directory, collecting `(relative_path, absolute_path)` pairs.
fn walk_dir(root: &Path, dir: &Path, entries: &mut Vec<(String, PathBuf)>) {
    let read_dir = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("Failed to read directory '{}': {}", dir.display(), e));

    for entry in read_dir {
        let entry = entry.expect("Failed to read directory entry");
        let path = entry.path();

        if path.is_dir() {
            walk_dir(root, &path, entries);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("Failed to strip prefix")
                .to_string_lossy()
                .replace('\\', "/");
            entries.push((rel, path));
        }
    }
}
