//! Runtime asset store — decompresses and serves embedded assets by path.

use std::collections::HashMap;
use flate2::read::GzDecoder;
use std::io::Read;

/// An entry in the embedded asset table generated by `build.rs`.
///
/// Each entry is a `(relative_path, gzip_compressed_bytes)` pair.
pub type EmbeddedAsset = (&'static str, &'static [u8]);

/// Runtime asset store. Holds decompressed asset data keyed by relative path.
///
/// ```ignore
/// engine.assets_mut().load_embedded(assets::ASSETS);
/// let bytes = engine.assets().get("textures/player.png").unwrap();
/// ```
pub struct AssetStore {
    assets: HashMap<String, Vec<u8>>,
}

impl AssetStore {
    /// Create an empty asset store.
    pub fn new() -> Self {
        Self {
            assets: HashMap::new(),
        }
    }

    /// Load a table of gzip-compressed embedded assets.
    ///
    /// Each entry is decompressed and stored by its relative path key.
    /// Call this once at startup (e.g. in `Game::init`).
    pub fn load_embedded(&mut self, table: &[EmbeddedAsset]) {
        for &(path, compressed) in table {
            let mut decoder = GzDecoder::new(compressed);
            let mut data = Vec::new();
            decoder
                .read_to_end(&mut data)
                .unwrap_or_else(|e| panic!("Failed to decompress asset '{}': {}", path, e));
            self.assets.insert(path.to_string(), data);
        }
    }

    /// Insert a raw (uncompressed) asset.
    ///
    /// Useful for tests and tools that load assets from the filesystem
    /// rather than from the build-time embedded table.
    pub fn insert(&mut self, path: impl Into<String>, data: Vec<u8>) {
        self.assets.insert(path.into(), data);
    }

    /// Get an asset's bytes by relative path.
    ///
    /// Returns `None` if the asset doesn't exist.
    pub fn get(&self, path: &str) -> Option<&[u8]> {
        self.assets.get(path).map(|v| v.as_slice())
    }

    /// Check if an asset exists.
    pub fn contains(&self, path: &str) -> bool {
        self.assets.contains_key(path)
    }

    /// Number of loaded assets.
    pub fn len(&self) -> usize {
        self.assets.len()
    }

    /// Whether the store is empty.
    pub fn is_empty(&self) -> bool {
        self.assets.is_empty()
    }

    /// Iterate over all asset paths.
    pub fn paths(&self) -> impl Iterator<Item = &str> {
        self.assets.keys().map(|s| s.as_str())
    }
}

impl Default for AssetStore {
    fn default() -> Self {
        Self::new()
    }
}
