use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

use crate::toolchain::{Invocation, Invoker};

pub struct AndroidBuildArgs {
    pub release: bool,
    pub profile: bool,
}

pub fn build(project_root: &Path, invoker: &dyn Invoker, args: AndroidBuildArgs) -> Result<()> {
    let gradle_dir = project_root.join("platform/android");
    ensure_local_properties(&gradle_dir);
    let task = if args.release { ":app:assembleRelease" } else { ":app:assembleDebug" };
    let mut inv = Invocation::new("./gradlew", &gradle_dir).arg(task);
    if args.profile {
        inv = inv.arg("-Pprofile=true");
    }
    let out = invoker.run(&inv.streaming())?;
    if out.status != 0 {
        anyhow::bail!("gradle failed (exit {}) — see output above", out.status);
    }
    Ok(())
}

/// Create `local.properties` from the user's Android SDK location if it
/// doesn't exist. Gradle requires `sdk.dir` to resolve the Android plugin;
/// auto-generating this removes a manual setup step. Silent failures are OK
/// — gradle will surface its own clear error if the SDK can't be found.
fn ensure_local_properties(gradle_dir: &Path) {
    let props = gradle_dir.join("local.properties");
    if props.exists() { return; }
    let Some(sdk) = find_android_sdk() else { return };
    let content = format!(
        "## Auto-generated by `unison build android`. Do not check in.\n\
         sdk.dir={}\n",
        sdk.display(),
    );
    let _ = fs::write(&props, content);
}

fn find_android_sdk() -> Option<PathBuf> {
    for var in ["ANDROID_HOME", "ANDROID_SDK_ROOT"] {
        if let Ok(v) = std::env::var(var) {
            let p = PathBuf::from(v);
            if p.exists() { return Some(p); }
        }
    }
    if let Ok(home) = std::env::var("HOME") {
        let p = PathBuf::from(home).join("Library/Android/sdk");
        if p.exists() { return Some(p); }
    }
    None
}
